name: CI - Build & Deploy

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::537976614557:role/Github
          aws-region: eu-north-1
      - name: Build & push image
        run: |
          docker build -t ghcr.io/mallarb20000/score-backend:$IMAGE_TAG ./backend
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/mallarb20000/score-backend:$IMAGE_TAG
      - name: Create EB bundle
        run: |
          sed "s/\${IMAGE_TAG}/$IMAGE_TAG/g" Dockerrun.aws.json > Dockerrun.aws.json
          zip -r deploy.zip Dockerrun.aws.json .ebextensions
      - name: Upload to S3
        run: aws s3 cp deploy.zip s3://scorespoken-assests-prod/deploy-$IMAGE_TAG.zip
      - name: Create EB version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name scorespoken-prod \
            --version-label $IMAGE_TAG \
            --source-bundle S3Bucket=scorespoken-assests-prod,S3Key=deploy-$IMAGE_TAG.zip \
            --region eu-north-1
      - name: Deploy
        run: |
          aws elasticbeanstalk update-environment \
            --application-name scorespoken-prod \
            --environment-name Scorespoken-prod-env-1 \
            --version-label $IMAGE_TAG \
            --region eu-north-1