name: CI - Build & Deploy

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend  # 👈 this is essential

    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python & Poetry
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run tests
        run: poetry run python manage.py test


      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/mallarb20000/score-backend:${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: docker push ghcr.io/mallarb20000/score-backend:${{ env.IMAGE_TAG }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::537976614557:role/Github
          aws-region: eu-north-1

      - name: Create deployment bundle (with docker-compose.yml)
        working-directory: .
        run: |
          echo "IMAGE_TAG=${{ env.IMAGE_TAG }}" > .env
          zip -r deploy.zip docker-compose.yml .env backend .ebextensions

      - name: Upload bundle to S3
        run: aws s3 cp deploy.zip s3://scorespoken-assests-prod/deploy-${{ env.IMAGE_TAG }}.zip

      - name: Create new Elastic Beanstalk app version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name Scorespoken-prod \
            --version-label ${{ env.IMAGE_TAG }} \
            --source-bundle S3Bucket=scorespoken-assests-prod,S3Key=deploy-${{ env.IMAGE_TAG }}.zip \
            --region eu-north-1

      - name: Deploy new version to Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --application-name Scorespoken-prod \
            --environment-name Scorespoken-prod-env \
            --version-label ${{ env.IMAGE_TAG }} \
            --region eu-north-1
