name: CI - Build & Deploy

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write
  id-token: write

env:
  IMAGE_TAG: ${{ github.sha }}
  GHCR_IMAGE: ghcr.io/mallarb20000/score-backend:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker + AWS OIDC credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::537976614557:role/Github
          aws-region: eu-north-1

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Docker Image
        run: |
          docker build -t $GHCR_IMAGE ./backend
          docker push $GHCR_IMAGE

      - name: Prepare deploy bundle (docker-compose only)
        run: |
          mkdir bundle
          echo "version: '3'" > bundle/docker-compose.yml
          echo "services:" >> bundle/docker-compose.yml
          echo "  web:" >> bundle/docker-compose.yml
          echo "    image: $GHCR_IMAGE" >> bundle/docker-compose.yml
          echo "    ports:" >> bundle/docker-compose.yml
          echo "      - '8000:8000'" >> bundle/docker-compose.yml
          zip -r deploy.zip bundle

      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://your-s3-bucket-for-beanstalk/deploy-${{ github.sha }}.zip

      - name: Create EB Application Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name Scorespoken-prod \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=your-s3-bucket-for-beanstalk,S3Key=deploy-${{ github.sha }}.zip \
            --region eu-north-1 \
            --process

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name Scorespoken-prod-env \
            --version-label ${{ github.sha }} \
            --region eu-north-1
