name: CI - Build & Deploy

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Lint
        run: poetry run python -m flake8 . || true  # Add flake8 to dev dependencies if needed
      - name: Test
        run: poetry run python manage.py test
      - name: Build Docker image
        run: docker build -t backend-test .

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm lint || true
      - name: Test
        run: pnpm test || true
      - name: Build Docker image
        run: docker build -t frontend-test .

  deploy-frontend:
    needs: frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy to Fly.io (Frontend)
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-backend:
    needs: backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Install Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy to Fly.io (Backend)
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_BACKEND }}
