# .github/workflows/ci.yml

name: CI-CD

on:
  push:
    branches: [ "master" ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/mallarb20000/score-backend:${{ env.IMAGE_TAG }} ./backend

      - name: Push Docker image
        run: docker push ghcr.io/mallarb20000/score-backend:${{ env.IMAGE_TAG }}

      - name: Set up deployment package
        run: |
          # The deployment package needs the docker-compose.yml at the root.
          # We are creating a zip file from the contents of the backend directory.
          cd backend
          zip -r ../deploy.zip .

      - name: Upload package to S3
        run: aws s3 cp deploy.zip s3://your-s3-bucket-for-beanstalk/deploy-${{ env.IMAGE_TAG }}.zip

      - name: Create new Elastic Beanstalk application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name Scorespoken-prod \
            --version-label ${{ env.IMAGE_TAG }} \
            --source-bundle S3Bucket="your-s3-bucket-for-beanstalk",S3Key="deploy-${{ env.IMAGE_TAG }}.zip" \
            --region eu-north-1

      - name: Deploy new version to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --application-name Scorespoken-prod \
            --environment-name Scorespoken-prod-env \
            --version-label ${{ env.IMAGE_TAG }} \
            --region eu-north-1